### ISSUE TITLE
Figure out best way to show columns types in both DataSource Page and the FeatureSets

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/workbench#218]
For the DataSource and FeatureSet subpages:

See comments at the bottom :)

**Comment by brifordwylie** [comment]
So the table creation is in 
`sageworks/src/sageworks/web_components`

There's an argument to the `create()` function
```
    column_types: dict = None,
```

Use this dictionary (which has column names/types)
- Types: string, int, float, timestamp

Anyway, there's probably some nice way to use `style_header_conditional` but I'd WAY rather just have each header have some HTML CLASS (based on type) and that way we can change colors/attributes in the CSS

When the column headers are created you can give them an "id"...  can we give them a "class"?

If we can give them a class then each column will get a class based on type
- header:float
- header:string
- etc

and then in the CSS we can set the background color based on those classes


![Image](https://github.com/SuperCowPowers/sageworks/assets/4806709/96e78f7f-d339-4ba2-92a5-d4b50e771656)

**Comment by giupb** [comment]
@luiztauffer suggestion: instead of coloring the headers, we could pop up the type of each column
