### ISSUE TITLE
Review Current Dash 'Multi-Page' Code and Organization

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/workbench#229]
The current mult-page AWS Dashboard application is our FIRST application (there will hopefully be a number of tailored, customized apps for clients). The way this application is set up is documented here:

- https://docs.google.com/presentation/d/116GRosKqHS3vBC8RdyJ9uGbZbHQe0Mgg6sac4l-0wZE/edit?usp=sharing

Review slides and then review the code

- sageworks/applications/aws_dashboard.  (Dash code)
- sageworks/src/sageworks/web_components (Plotly 'graphs/figures')
- sageworks/src/sageworks/views (The components that isolate the gathering of AWS services data)

**Comment by luiztauffer** [comment]
@brifordwylie 
Here’s a mock for an improved organization of the multi-page app:

```
pages/
…./page_xx
……../assets/              (page-specific assets)
……../components/          (page-specific Dash components )
……../callbacks.py         (components actions, either interactions with other components or with "backend")
……../layout.py            (organization and style of visual elements)
……../page.py              (this page’s main script)
…./page_yy
……../ …. 
…./assets/         (shared assets)
…./components/     (shared Dash components)
…./services/       ("backend" functions)
…./clients/        (e.g. SageWorksClient, basically sageworks.views)
…./app.py          (main Dash app script)
…./requirements.txt
…./Dockerfile
…./README.md
```

With an organization similar to this we would be achieving:
- modularization and standardization of page-specific content (callbacks, layouts, assets)
- standardization of shared resources (components, assets, clients, services, etc…)
- helps us with a better separation of concerns between backend logic (services, clients) and the frontend logic (callbacks and layout)
- definition of app’s dependencies (requirements.txt), documentation (README.md) and containerization (Dockerfile) to improve distribution and re-usability of the aws web server

All those changes might be too much to do right now, though. We should consider the priorities of the SageWorks project as a whole.

Open questions:
- should we rename `/sageworks/web_components ` to `/sageworks/graphic_components`?
- each web_component depends on the information of at least one View to be used. How do we formalize these dependencies? E.g. if web_components are specific to just one View, we probably would like to have this dependency explicitly reflected in the project’s organization as well, with folders for each view with a sub-folder /webcomponents for all visual components related to that view

**Comment by brifordwylie** [comment]
@luiztauffer this looks good. Lets use the proposed file/directory reorg above 👍
