### ISSUE TITLE
Blank Dashboard while loading web_components

### ISSUE THREAD

**Issue by luiztauffer** [SuperCowPowers/workbench#246]
While fetching Views data for the web_components, tables are not filled and we get a blank Dashboard, which creates a bad impression of something not working right, or missing resources. The data eventually appears, bu we could perhaps indicate with a loading spinner that the fetching is still in progress.

![image](https://github.com/SuperCowPowers/sageworks/assets/24541631/a6f0b21e-1496-4444-a750-62f743c0d3d9)

**Comment by brifordwylie** [comment]
This has been fixed... the tables now have status text that says 'Waiting for data...'
