### ISSUE TITLE
Violin Plot 'growth' logic

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/workbench#257]
Okay, so when the violin plot has just a few plots the current height is fine, but where there's lots of plots it should grow in height so that the plots are 'smooshed'

<img width="1468" alt="Screenshot 2023-06-07 at 11 32 21 AM" src="https://github.com/SuperCowPowers/sageworks/assets/4806709/72915038-93f2-42f6-9700-654fa642d75e">

**Comment by luiztauffer** [comment]
@brifordwylie we can define the figure height based on the number of rows * <min-height>
this should work well enough I believe. Unfortunately I don't think we can directly set the dimensions of the subplots in pixels.

**Comment by brifordwylie** [comment]
@luiztauffer seems good.. there's an internal calculation for the number of rows... so we could just use that to change the figure height... I'm not sure how to change the figure height.. but I'm sure you know :)
