### ISSUE TITLE
Details artifact page always loads the first row

### ISSUE THREAD

**Issue by giupb** [SuperCowPowers/workbench#260]
Regardless of the row clicked on a specific artifact table on the home page, when the artifact page loads, it always displays the data from the first row of that artifact table.

For example, if I click on the second row of the Data Sources table, when the Data Sources details page loads, it displays the details of the first Data Source:
![image](https://github.com/SuperCowPowers/sageworks/assets/52609794/ea759fb0-c0d7-4975-8c1d-42c5bef02320)
![image](https://github.com/SuperCowPowers/sageworks/assets/52609794/bab13b97-ea9f-4a0a-9de3-208785bfd93d)

It would be great if, when the user clicks on a specific artifact on an artifact table, the details page shows the details of that specific artifact instead of the first one.

**Comment by brifordwylie** [comment]
Loading the first row when the page reloads is probably fine. Folks shouldn't be reloading the page :)
