### ISSUE TITLE
Reduce white space around trash can

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/workbench#263]
Let's keep the UI 'tight'.... lets minimize the white space around the trash can and keep that column small.

<img width="143" alt="Screenshot 2023-06-12 at 3 34 40 PM" src="https://github.com/SuperCowPowers/sageworks/assets/4806709/4d134baa-464f-423d-afcd-887cd4cd9461">

**Comment by giupb** [comment]
Issue adressed in the PR #266
