### ISSUE TITLE
Gray Box around Meta Data is not aligned and doesn't look good

### ISSUE THREAD

**Issue by brifordwylie** [SuperCowPowers/workbench#264]
Sorry, I know this is probably opinion but I don't like the grey box around the meta data.. it looks bad IMO, so lets revert back to the original functionality.

<img width="1177" alt="Screenshot 2023-06-12 at 3 40 29 PM" src="https://github.com/SuperCowPowers/sageworks/assets/4806709/4239c77b-70f5-40d2-b333-c5f0fc62ea50">

![screenshot_2023-05-17_at_3 19 50_pm_720](https://github.com/SuperCowPowers/sageworks/assets/4806709/4233b5fb-6707-4d9d-bdef-12a9a3f8874a)

**Comment by giupb** [comment]
Sorry, I made these changes on my own, but just undo them.
Already in the main! :)
